env:
  browser: true
  es6: true
extends:
  - airbnb
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins:
  - jest
  - react
rules:
  brace-style:
    - error
    - stroustrup
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  no-console: 0

  react/jsx-indent:
    - error
    - 4

  react/jsx-indent-props:
    - error
    - 4

  react/jsx-filename-extension:
    - off

  jsx-a11y/label-has-for: # Seems to bug
    - off

  jsx-a11y/anchor-is-valid:
    - error
    - component: a
      specialLink:
        - hrefLeft
        - hrefRight
      aspect:
        - noHref
        - invalidHref

